### ISSUE TITLE
Remove support for Fluent 0.4 syntax from python-fluent

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#106]
[Fluent 0.5](https://github.com/projectfluent/fluent/releases/tag/v0.5.0) was released in January 2018, let's remove the 0.4 syntax code-paths in the python Fluent parser.

Notably, that's old-style comments, tags?, sections and enforced `=`.

@stasm, happy to help here, unless you're like _I waited to write this patch for a year, don't take it away from me_.

CC @spookylukey @zbraniecki @hkasemir

**Comment by stasm** [comment]
Thank you for filing this issue. I appreciate the offer to help. I'll be happy to r+ the PR, if you'd like to open it :)

**Comment by Pike** [comment]
Taking.

**Comment by Pike** [comment]
This was fixed by #107
