### ISSUE TITLE
Harmonize fluent.runtime API with bundle.formatPattern

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#118]
This is in line with what we do in js and rust:

https://github.com/projectfluent/fluent.js/pull/380
https://github.com/projectfluent/fluent-rs/issues/119

@spookylukey, I could pick that up, if you don't mind?

**Comment by spookylukey** [comment]
@Pike That's fine with me. I haven't been able to follow the recent discussions closely, and I'm not likely to be very active with fluent for a while (3rd child born etc. etc.).

**Comment by Pike** [comment]
This has a PR in #121.

**Comment by Pike** [comment]
#121 landed on the `next-gen-api` branch.
