### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by alehuo** [projectfluent/python-fluent#134]
**Edit: It appeared that the `fluent.runtime` I installed with `pip install fluent.runtime` was actually a lot older than what I expected.**

When adding messages to Fluent bundles, the documentation at https://fluent-runtime.readthedocs.io/en/latest/index.html states you can directly add the messages as a template string like so:

```python3
>>> bundle.add_messages("""
... welcome = Welcome to this great app!
... greet-by-name = Hello, { $name }!
... """)
```

In reality, you have to wrap the template string into a `FluentResource` and use `bundle.add_resource` instead of `bundle.add_messages` because it does not exist. The `add_resource` function checks if there is a `body` key in the `resource` function parameter, which is generated by the `FluentResource` class.

```python3
from fluent.runtime import FluentBundle, FluentResource

bundle = FluentBundle(['en-us'])
bundle.add_resource(FluentResource("""
welcome = Welcome!
"""))
```

Also, `bundle.format()` does not exist.

**Comment by Pike** [comment]
The currently available release is 0.3, and its documentation is at https://github.com/projectfluent/python-fluent/blob/next-gen-api/fluent.runtime/docs/usage.rst.

Sadly, I don't have access to rtd, so I can't update the docs hosted there.

**Comment by alehuo** [comment]
Thank you, I thought about many reasons why I couldn't get this to work with the docs at rtd.

Could you add a notification to the master branch's README.md that developers should follow the documentation listed in the `next-gen-api` branch?

**Comment by stasm** [comment]
Or we could merge that branch to `master` :) We've been using this API in `fluent.js` and `fluent-rs` for 6 months now, see the `@fluent/bundle` changelog for example. It would be great to unify `fluent.runtime`'s API, too. @Pike What do you think?

**Comment by Pike** [comment]
We should discuss merging to master. But the configured hook is out of date, and we need a secret from rtd.

https://docs.readthedocs.io/en/latest/webhooks.html#webhook-deprecated-endpoints for details.

**Comment by spookylukey** [comment]
If you let me know your username on RTD I can add you as an admin. I don't have admin rights to the GitHub project to be able to set it up myself.
