### ISSUE TITLE
Use github actions for automation

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#137]
Let's consider to switch to gh actions for our automation of python-fluent.

Our travis setup is rather involved, and also over-tests.

Looking at the documentation of gh actions, we'll have a ton of nice things there.

**Comment by Pike** [comment]
Sadly, we can't test actions in PRs. We'll need to add workflows, and then we can iterate on the workflows. (That's by design, I learned, so PRs can't attack master)

I have a WIP (#140 ) that tries to lint. Only the code, not tests, as those don't pass. @stasm, should we start from there?

Obviously, I'll need to restore the travis config for now.

The idea would be to add GH actions until we have everything we want there, and then drop travis.

**Comment by stasm** [comment]
Starting with a minimal GH Action workflow sounds good to me.

**Comment by Pike** [comment]
This is done now.
