### ISSUE TITLE
Move Visitor and Transformer out of ast.py

### ISSUE THREAD

**Issue by stasm** [projectfluent/python-fluent#141]
I'd like to consider making `ast.py` strictly about AST nodes. The processing classes could be moved to another module: `tools.py`, `visitor.py`, `process.py` or something else.

**Comment by Pike** [comment]
I briefly glanced at this, and then recognized that this is a breaking API change. Currently, consumers import them from `ast`, and if we tried to continue to expose them there, stuff would break :-(.

But yeah, we can do this in a new release of `fluent.syntax`.

**Comment by stasm** [comment]
Yep, that's why I filed a new issue about this, to discuss this independently of #139.
