### ISSUE TITLE
Publish python-fluent packages after doc updates

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#152]
Now that we have docs and READMEs with long descriptions worth that name, let's update the packages and upload to pypi.

My gut-instinct says that we're close to 1.0 versions. @stasm might like the idea.

I'm a bit hesitant to do that for fluent.syntax and fluent.runtime, given how much we changed, but I think they're also in RC state.

For fluent.pygments, I wouldn't mind going to 1.0 directly.

**Comment by Pike** [comment]
Proposal:

- fluent.syntax: 0.18.0
- fluent.runtime: 0.....
- fluent.pygments: 1.0

Actually, runtime might be OK to just wait a couple more days. There's been comments on #136 that are good to revisit.

How about 0.3.1 for that? It's really just doc changes there.

**Comment by stasm** [comment]
That's a reasonable versioning proposal, I like it!

**Comment by Pike** [comment]
Landed that as https://github.com/projectfluent/python-fluent/commit/fc2a652bfad927f9589582fdd999504fbdfc352b.
