### ISSUE TITLE
Drop support for Python 2.7 and 3.5

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#162]
... and update our testing and compat matrix beyond 3.5, too.

This should be done syntax first, and then the other two.

**Comment by Pike** [comment]
As we're breaking compat, should we also move from pgkutil-style namespace packages to native ones?

This would be a good time, as we could just generally bump mutual requirements on all three packages. Also for fluent.migration, I guess.

https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages

**Comment by sandalwoodbox** [comment]
Was this resolved by https://github.com/projectfluent/python-fluent/pull/161 & https://github.com/projectfluent/python-fluent/pull/163?

**Comment by eemeli** [comment]
As noted above, support for Python < 3.6 has already been dropped.
