### ISSUE TITLE
Incorrect handling of tabs in message value

### ISSUE THREAD

**Issue by eemeli** [projectfluent/python-fluent#173]
As identified in https://github.com/mozilla/pontoon/issues/2470#issuecomment-1107451952, this happens:

```python
from fluent.syntax import ast, FluentParser, FluentSerializer
parser = FluentParser()
serializer = FluentSerializer()

string = """places-open-in-container-tab =
    .label = Բացել նոր ներդիրում
    .accesskey =	
"""

string
'places-open-in-container-tab =\n    .label = Բացել նոր ներդիրում\n    .accesskey = \t\n'

serializer.serialize(parser.parse(string))
'places-open-in-container-tab =\n    .label = Բացել նոր ներդիրում\n    .accesskey = \n'
```

Tabs should not be lost; they count as valid `inline_text` characters according to the [spec](https://github.com/projectfluent/fluent/blob/master/spec/fluent.ebnf).

**Comment by Pike** [comment]
Probably also a bug in js syntax parser, and the runtime parser.

**Comment by eemeli** [comment]
Yeah, will need to check all the implementations.
