### ISSUE TITLE
No release for fluent.runtime 0.4.0

### ISSUE THREAD

**Issue by GetPsyched** [projectfluent/python-fluent#187]
`fluent.runtime` 0.4.0 is released as mentioned in the [changelogs](https://github.com/projectfluent/python-fluent/blob/main/fluent.runtime/CHANGELOG.rst) but it isn't released as a tag.

I want this to be fixed because I am making a Nix package for this project and it would be convenient and more reliable to work with tags instead of commit hashes.

**Comment by eemeli** [comment]
The tag you're looking for is [`fluent.syntax@0.19.0`](https://github.com/projectfluent/python-fluent/releases/tag/fluent.syntax%400.19.0).

**Comment by GetPsyched** [comment]
Weird. Does it not show up in releases because there is no changelog?

**Comment by eemeli** [comment]
The tags were there, they were just not marked as "releases" in GitHub.
