### ISSUE TITLE
Release fluent.pygments 1.1? or 2.0?

### ISSUE THREAD

**Issue by GetPsyched** [projectfluent/python-fluent#196]
The `fluent.pygments` hasn't got an update in over 2.5 years. It's still version `1.0` in PyPI as well as here, even though there has been an update to it after that release.

Is there a reason for this?

**Comment by eemeli** [comment]
The changes to `fluent.pygments` since its 1.0 release have been entirely stylistic, as it's just a thin wrapper on top of `fluent.syntax`. So there hasn't been any need to release a new update since then.

**Comment by eemeli** [comment]
No; `fluent.pygments` depends on `fluent.runtime`, though.

**Comment by GetPsyched** [comment]
Okay, thanks!

**Comment by GetPsyched** [comment]
> No; `fluent.pygments` depends on `fluent.runtime`, though.

But `setup.cfg` says it depends on `fluent.syntax`?

https://github.com/projectfluent/python-fluent/blob/bc5b0e52a059944503ff2624b8d0f9c285d81016/fluent.pygments/setup.cfg#L10

**Comment by eemeli** [comment]
Oh, drat, sorry, yes, it depends on `fluent.syntax` and not `fluent.runtime`. Which is what I meant to write earlier, but clearly didn't.
