### ISSUE TITLE
tests don't work in py3.6

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/python-fluent#21]
I spent a good 2 hours today trying to understand why my patch breaks tests.

The two things that made it really hard were:

1) In py2.7 when json doesn't match expected the diff contains all `u'foo' != 'foo'` which is terribly misleading.
2) py3.6 did not report any errors.

The combination of those two led me onto the path of trying to discover if I changed somehow encoding of the tests, because only py2.7 seemed to be affected.

If we can't fix (1), can we at least fix (2) please?

STR:

1) Change any of the fixture_structure json files, for example span start or end.
2) run tox -e py36

Current result:
No error reported

Expected result:
Error reported

**Comment by Pike** [comment]
The problem is that py36 doesn't find any tests in either test_behaviour or test_structure, the meta foo in that test case isn't producing the right tests.

six can help, http://python-future.org/compatible_idioms.html#metaclasses
