### ISSUE TITLE
Remove MESSAGE_REFERENCE and EXTERNAL_ARGUMENT helpers

### ISSUE THREAD

**Issue by stasm** [projectfluent/python-fluent#43]
The [`helpers.py`](https://github.com/projectfluent/python-fluent/blob/b40264348efe0dbad0565678533c24c21a2c4b0e/fluent/migrate/helpers.py) file currently defines two pseudo-AST nodes which can be used in migration specs:  `MESSAGE_REFERENCE` and `EXTERNAL_ARGUMENT`. I'd like to discuss the general approach regarding such helpers.

On one hand the allow to write more concise AST in migrations. On the other, they introduce abstractions which need to be learned besides the AST itself in order to write and maintain migrations. This in turn results in situations when it's tempting to randomly try different combinations of the helpers to see if they fix an issue with the migration :)

AST being the source of truth, I think there's value in sticking to it exclusively, even at the cost of increased verbosity.

@flodolo, @Pike, @zbraniecki - What do you think?

I already see @zbraniecki not use the helpers in [bug 1424682](https://bugzilla.mozilla.org/show_bug.cgi?id=1424682) in some cases, like here:

```py
FTL.Message(
    id = FTL.Identifier('category-general'),
    attributes = [
        FTL.Attribute(
            FTL.Identifier('tooltiptext'),
            FTL.Pattern(
                elements = [
                    FTL.Placeable(
                        # This could read:
                        # expression=MESSAGE_REFERENCE('pane-general-title')
                        expression = FTL.MessageReference(
                            id = FTL.Identifier(
                                'pane-general-title'
                            )
                        )
                    )
                ]
            )
        )
    ]
)
```

This is also related to what the API of `REPLACE` and `CONCAT` should be. Should we only accept `Patterns` and `PatternElements` (i.e. `TextElements` and `Placeables`)? This would make the API closer to the AST. Or should we accept `Expressions` as well? Compare:

```py
# REPLACE converts the MessageReference expression returned by the helper to a Placeable.
FTL.Message(
    id = FTL.Identifier('help-button-label'),
    value = REPLACE(
        'browser/chrome/browser/preferences/preferences.dtd',
        'helpButton2.label',
        {
            '&brandShortName;': MESSAGE_REFERENCE('-brand-short-name')
        }
    )
)
```

```py
# REPLACE requires an explicit Placeable wrapping the MessageReference expression.
FTL.Message(
    id = FTL.Identifier('help-button-label'),
    value = REPLACE(
        'browser/chrome/browser/preferences/preferences.dtd',
        'helpButton2.label',
        {
            '&brandShortName;': FTL.Placeable(
                MESSAGE_REFERENCE('-brand-short-name')
            )
        }
    )
)
```

```py
# REPLACE requires an explicit Placeable and an explicit MessageReference.
FTL.Message(
    id = FTL.Identifier('help-button-label'),
    value = REPLACE(
        'browser/chrome/browser/preferences/preferences.dtd',
        'helpButton2.label',
        {
            '&brandShortName;': FTL.Placeable(
                FTL.MessageReference(
                    FTL.Identifier('-brand-short-name')
                )
            )
        }
    )
)
```

**Comment by zbraniecki** [comment]
I see a value in those helpers. They're useful when I work on simple cases. I'm not in favor of removing them, but won't fight if you decide to :)

**Comment by stasm** [comment]
OK, let's leave them. I'm just going to remove them from being exported directly by `fluent.migrate`.
