### ISSUE TITLE
Unable to serialize JSON

### ISSUE THREAD

**Issue by mathjazz** [projectfluent/python-fluent#5]
The old (l20n) parser returned JSON, which Pontoon used internally, and the serializer took it.

The new parser returns an object and the serializer takes it as input. Since we still use JSON for storing AST in Pontoon, we need a method to conver AST object to JSON (already exists) and JSON to AST object (doesn't exist yet).

**Comment by Pike** [comment]
Out of curiousity, is this just server-side python, or do you need these APIs on the client-side js, too?

**Comment by mathjazz** [comment]
In my use case it's only server side. On the client I only need a parser.

**Comment by stasm** [comment]
I opened #6 which has a fix for this.

> Out of curiousity, is this just server-side python, or do you need these APIs on the client-side js, too?

This shouldn't be required in client-side JS as long as you use `node.type === 'NodeName'` rather than `node instanceof NodeName` in your code.

**Comment by mathjazz** [comment]
Confirming that this works now!
