### ISSUE TITLE
Use flake8

### ISSUE THREAD

**Issue by spookylukey** [projectfluent/python-fluent#64]
How do you feel about adding flake8 to the project? I never code in Python without it. It looks like the vast majority of the code base already conforms - mainly it complains about some imports not being at the top of the module. This seems to be because of some sys.path hackery in the tests that I don't understand the purpose of - if I remove those lines, the tests still run fine.

So there are two questions I guess:
- would you accept a PR that makes flake8 compliance a part of the test suite and TravisCI?
- can I remove the sys.path hackery and fix the other remaining issues that flake8 complains about?

**Comment by Pike** [comment]
> would you accept a PR that makes flake8 compliance a part of the test suite and TravisCI?

I think that the current master if flake8 compliant, the tests are not. I'd love to see that eventually. Maybe not now. 'Cause I just took a stab at #72, which will change tests quite a bit.

> can I remove the sys.path hackery and fix the other remaining issues that flake8 complains about?

Yeah, though I might beat you to it ;-)
