### ISSUE TITLE
parser could be pythonic and performant

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#72]
The current parser in `fluent.syntax.parser` closely matches the js parser, and python doesn't cope with that well.

We could make that more pythonic.

I also think that we can implement the backwards-compat part of the parser as a subclass, so tools and deployments that just want current fluent don't need to accept files that are no-more-cool in fluent today.

I'll take a stab at this, let's see how it goes.

**Comment by stasm** [comment]
This sounds great! I can't wait to see what you come up with! 🎉

**Comment by Pike** [comment]
I don't think this is worth doing at this point, closing out. There might be smaller changes to improve performance that are not what I had in mind here.
