### ISSUE TITLE
Update fluent.runtime to fluent.syntax 0.10

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#86]
Filing an issue for @spookylukey's work in https://github.com/django-ftl/python-fluent/compare/master...bundle_fluent_syntax_08.

Luke, is this something that's ready to look at? Related, this probably wants a squash, but does it also want a split into multiple commits?

**Comment by spookylukey** [comment]
I think it is ready to look at - I don't remember there being anything outstanding.

I don't think there is a great benefit in having multiple commits - the only two logically separate bits from the current perspective are:

1. Updates for new AST for existing Fluent features (more than once, IIRC)
2. New Fluent features (especially parameterized terms).

But you could also just lump all these together in a single "Updates for fluent.syntax 0.10". It might be hard to untangle now, especially with all the moving of folders. So I'd suggest squashing to a single commit.

**Comment by Pike** [comment]
A single squashed commit sounds great, thanks.
