### ISSUE TITLE
Don't use Tox in Travis

### ISSUE THREAD

**Issue by stasm** [projectfluent/python-fluent#89]
According to https://docs.travis-ci.com/user/languages/python/#travis-ci-uses-isolated-virtualenvs, using both Travis and Tox isn't well supported. Travis already runs all tests from the matrix in separate virtualenvs. Can we drop Tox?

**Comment by Pike** [comment]
I like testing in tox, because that's what works locally. Like, I don't see how you can test fluent-runtime locally w/out installing both fluent.syntax and fluent.runtime into a virtualenv.

**Comment by spookylukey** [comment]
We could use tox for local testing and just make Travis do something different. We don't have a particularly complex setup, so the bit of duplication involved shouldn't be too hard to manage.

**Comment by stasm** [comment]
Alright, this makes sense. Thank you to both of you for your input. Let's add Python 3.7 to Travis in #70 and then, let's try to drop Tox from `.travis.yml` in this issue. We'll leave Tox for local testing.

**Comment by Pike** [comment]
I'm closing this, 'cause we're not using tox in travis.

Not that our `.travis.yml` is in good shape, but that's a different bug.
