### ISSUE TITLE
FluentDateTime inheriting from datetime breaks self.replace on pypy >= 5.10

### ISSUE THREAD

**Issue by Pike** [projectfluent/python-fluent#90]
pypy changed how `.replace` creates a new instance, by instantiating type(self).

Which ends up being a `FluentDateTime`, which doesn't take the positional arguments that datetime does.

@spookylukey, is this something you could tackle? I managed to reproduce this in the existing test suite on pypy3.5 6.0, but I'm not sure I understand how you're using kwargs in the `__new__` and `_init`.

This blocks updating our python testing setup in #70 .

**Comment by spookylukey** [comment]
Yes, I was aware of this issue with recent PyPy. I hadn't got round to working out if it was a bug in PyPy, or something we can work around. I can take a look.
